
class CResponse(object) :
    def __init__(self, submitted=None, response=None, taskid=None, hitid=None, workerid=None):
        self.submitted = submitted # date
        self.response = response # list of data generated by QType
        self.taskid = taskid
        self.hitid = hitid
        self.workerid = workerid
    @classmethod
    def deserialize(cls, d) :
        return CResponse(submitted=d['submitted'],
                         response=d['response'],
                         taskid=d['taskid'],
                         hitid=d['hitid'],
                         workerid=d['workerid'])
    def serialize(self) :
        return {'submitted' : self.submitted,
                'response' : self.response,
                'taskid' : self.taskid,
                'hitid' : self.hitid,
                'workerid' : self.workerid}
